spring.config.import=optional:file:.env[.properties]

spring.application.name=EventSync
security.jwt.token.secret-key=${JWT_TOKEN}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

server.port=443
server.ssl.key-store=${KEY_STORE}
server.ssl.key-store-password=${HTTPS_PASS}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=eventsync

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc=DEBUG