spring.application.name=EventSync

# Sécurité (Ton JWT tel quel)
security.jwt.token.secret-key=a1b2c3d4-5678-90ab-cdef-1234567890ab

# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsync_db
spring.datasource.username=eventsync_manager
# IMPORTANT : On ne met pas de guillemets ici, même avec le #
spring.datasource.password=#Ptar&d78eP-7MfP_Cd5
spring.datasource.driver-class-name=org.postgresql.Driver

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc=DEBUG