spring.application.name=EventSync
security.jwt.token.secret-key=96a4fda9-829d-4fd1-a0aa-8668f6a594e5

spring.datasource.url=jdbc:postgresql://localhost:5432/eventsync_db
spring.datasource.username=eventsync_manager
spring.datasource.password=#Ptar&d78eP-7MfP_Cd5
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc=DEBUG
