CREATE DATABASE eventsync_db;
CREATE ROLE eventsync_manager LOGIN ENCRYPTED PASSWORD '#Ptar&d78eP-7MfP_Cd5' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
\c eventsync_db
CREATE SCHEMA IF NOT EXISTS eventsync_app AUTHORIZATION eventsync_manager;
GRANT USAGE ON SCHEMA eventsync_app TO eventsync_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA eventsync_app TO eventsync_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA eventsync_app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eventsync_manager;